# Generated by Django 5.0.4 on 2024-04-27 07:59

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='image of EducationalGroup'),
        ),
        migrations.AlterField(
            model_name='educationalgroup',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='image of EducationalGroup'),
        ),
        migrations.AlterField(
            model_name='educationvideos',
            name='video',
            field=models.FileField(upload_to=utils.FileUpload.upload_to, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='image of teacher'),
        ),
    ]
