# Generated by Django 5.0.4 on 2024-04-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_education_image_alter_educationalgroup_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='education',
            name='group',
        ),
        migrations.RemoveField(
            model_name='education',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='educationfeature',
            name='education',
        ),
        migrations.RemoveField(
            model_name='educationvideos',
            name='education',
        ),
        migrations.RemoveField(
            model_name='educationalgroup',
            name='group_parent_educational',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='educational_group',
        ),
        migrations.RemoveField(
            model_name='educationfeature',
            name='feature',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='EducationVideos',
        ),
        migrations.DeleteModel(
            name='EducationalGroup',
        ),
        migrations.DeleteModel(
            name='EducationFeature',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
