# Generated by Django 5.0.4 on 2024-04-27 08:22

import django.db.models.deletion
import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_teacher_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100)),
                ('image_educational_groups', models.ImageField(upload_to=utils.FileUpload.upload_to)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='product.educationalgroup')),
            ],
            options={
                'verbose_name': 'educational_group',
                'verbose_name_plural': 'educational_groups',
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
