# Generated by Django 5.0.4 on 2024-04-27 08:27

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='feature_name')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AlterField(
            model_name='educationalgroup',
            name='image_educational_groups',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AddField(
            model_name='feature',
            name='educational_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_group_features', to='product.educationalgroup', verbose_name='educational_group'),
        ),
    ]
