# Generated by Django 5.0.4 on 2024-04-27 08:38

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_teachers_delete_teacher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AlterField(
            model_name='educationalgroup',
            name='image_educational_groups',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
    ]
