# Generated by Django 5.0.4 on 2024-05-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountbasketdetails',
            old_name='product',
            new_name='education',
        ),
    ]
