# Generated by Django 5.0.4 on 2024-05-07 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0031_alter_education_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.education')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
