# Generated by Django 5.0.4 on 2024-05-08 11:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customer_image'),
        ('cart', '0001_initial'),
        ('product', '0034_alter_education_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(auto_now=True)),
                ('is_finaly', models.BooleanField(default=False)),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.customer')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details_2', to='product.education')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details_1', to='cart.order')),
            ],
            options={
                'verbose_name': 'order detail',
                'verbose_name_plural': 'order details',
            },
        ),
    ]
