# Generated by Django 5.0.4 on 2024-05-08 11:19

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to),
        ),
    ]
